apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: elastic3
  name: elastic3
  namespace: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      run: elastic3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: elastic3
      labels:
        run: elastic3
      namespace: elastic
    spec:
      containers:
        - image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
          imagePullPolicy: Always
          name: elastic3
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: cluster.name
              value: elastic
            - name: node.name
              value: elastic3
            - name: network.host
              value: "0.0.0.0"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: discovery.seed_hosts
              value: "elastic1:9300"
            - name: cluster.initial_master_nodes
              value: "elastic1:9300"
          ports:
            - name: publish
              containerPort: 9200
              protocol: TCP
            - name: node
              containerPort: 9300
              protocol: TCP
          volumeMounts:
            - name: elastic3-data
              mountPath: /usr/share/elasticsearch/data
          resources:
            requests:
              memory: "2048Mi"
              cpu: "2"
            limits:
              memory: "2048Mi"
              cpu: "2"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: elastic3-data
          persistentVolumeClaim:
            claimName: elastic3-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: elastic3
  name: elastic3
  namespace: elastic
spec:
  ports:
    - name: external
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: internal
      port: 9300
      protocol: TCP
      targetPort: 9300
  selector:
    run: elastic3
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic3-data-pv
  namespace: elastic
spec:
  storageClassName: host
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/private/tmp/kube-deploys/elastic/data/elastic3"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic3-data-pvc
  namespace: elastic
spec:
  storageClassName: host
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi