apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: elastic1
  name: elastic1
  namespace: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      run: elastic1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: elastic1
      labels:
        run: elastic1
      namespace: elastic
    spec:
      containers:
        - image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
          imagePullPolicy: Always
          name: elastic1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: cluster.name
              value: "elastic"
            - name: node.name
              value: "elastic1"
            - name: network.host
              value: "0.0.0.0"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: discovery.seed_hosts
              value: "elastic1,elastic2,elastic3"
            - name: cluster.initial_master_nodes
              value: "elastic1,elastic2,elastic3"
          ports:
            - name: publish
              containerPort: 9200
              protocol: TCP
            - name: node
              containerPort: 9300
              protocol: TCP
          volumeMounts:
            - name: elastic1-data
              mountPath: /usr/share/elasticsearch/data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: elastic1-data
          persistentVolumeClaim:
            claimName: elastic1-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: elastic1
  name: elastic1
  namespace: elastic
spec:
  ports:
    - name: external
      port: 9201
      protocol: TCP
      targetPort: 9200
    - name: inernal
      port: 9301
      protocol: TCP
      targetPort: 9300
  selector:
    run: elastic1
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic1-data
  namespace: elastic
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/hardikpatel/workbench/projects/kube-deploys/elastic/data/elastic1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic1-data
  namespace: elastic
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  volumeName: elastic1-data
  resources:
    requests:
      storage: 1Gi