apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kibana
  name: kibana
  namespace: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kibana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: kibana
      labels:
        run: kibana
      namespace: elastic
    spec:
      containers:
        - image: docker.elastic.co/kibana/kibana:7.13.2
          imagePullPolicy: Always
          name: kibana
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: ELASTICSEARCH_HOSTS
              value: '["http://elastic1.elastic:9200","http://elastic2.elastic:9200","http://elastic3.elastic:9200"]'
            - name: server.host
              value: "0.0.0.0"
          ports:
            - name: publish
              containerPort: 5601
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: kibana
  name: kibana
  namespace: elastic
spec:
  ports:
    - name: external
      port: 5601
      protocol: TCP
      targetPort: 5601
  selector:
    run: kibana
  type: LoadBalancer