apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: opensearch-certs
  name: opensearch-certs
  namespace: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      run: opensearch-certs
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: opensearch-certs
      labels:
        run: opensearch-certs
      namespace: opensearch
    spec:
      initContainers:
        - name: set-vm-max-map-count
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
          - sysctl
          - -w
          - vm.max_map_count=262166
          securityContext:
            privileged: true
            runAsUser: 0
            runAsNonRoot: False
        - name: chown
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"] 
          args: ["-c", "chown -R 1000:1000 /usr/share/opensearch/data"] 
          volumeMounts:
            - name: opensearch-certs-data
              mountPath: /usr/share/opensearch/data
          securityContext:
            privileged: true
            runAsUser: 0
            runAsNonRoot: False
      containers:
        - image: busybox
          imagePullPolicy: Always
          name: opensearch-certs
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/share/opensearch/data
              name: opensearch-certs-data
            - mountPath: /usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml
              subPath: config.yml
              name: security-config
            - mountPath: /usr/share/opensearch/plugins/opensearch-security/securityconfig/generatecerts.sh
              subPath: generatecerts.sh
              name: security-config
          securityContext:
            privileged: true
            runAsUser: 1000
            runAsGroup: 0
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: opensearch-certs-data
          persistentVolumeClaim:
            claimName: opensearch-certs-data-pvc
        - name: security-config
          configMap: 
            name: opensearch-configmap
            items:
              - key: securityconfig.yml
                path: config.yml
              - key: generatecerts.sh
                path: generatecerts.sh
                mode: 0777
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: opensearch-certs
  name: opensearch-certs
  namespace: opensearch
spec:
  ports:
    - name: external
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: internal
      port: 9300
      protocol: TCP
      targetPort: 9300
  selector:
    run: opensearch-certs
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-certs-data-pvc
  namespace: opensearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi