apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: opensearch2
  name: opensearch2
  namespace: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      run: opensearch2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: opensearch2
      labels:
        run: opensearch2
      namespace: opensearch
    spec:
      initContainers:
        - name: set-vm-max-map-count
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
          - sysctl
          - -w
          - vm.max_map_count=262166
          securityContext:
            privileged: true
            runAsUser: 0
            runAsNonRoot: False
        - name: chown
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"] 
          args: ["-c", "chown -R 1000:1000 /usr/share/opensearch/data"] 
          volumeMounts:
            - name: opensearch2-data
              mountPath: /usr/share/opensearch/data
            - mountPath: /usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml
              subPath: config.yml
              name: security-config
            - mountPath: /usr/share/opensearch/plugins/opensearch-security/securityconfig/generatecerts.sh
              subPath: generatecerts.sh
              name: security-config
          securityContext:
            privileged: true
            runAsUser: 0
            runAsNonRoot: False
      containers:
        - image: opensearchproject/opensearch:latest
          imagePullPolicy: Always
          name: opensearch2
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: cluster.name
              value: opensearch
            - name: node.name
              value: opensearch2
            - name: node.master
              value: "true"
            - name: node.data
              value: "true"
            - name: node.ingest
              value: "true"
            - name: network.host
              value: "0.0.0.0"
            - name: transport.port
              value: "9300"
            - name: plugins.security.allow_unsafe_democertificates
              value: "true"
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: discovery.seed_hosts
              value: "opensearch1,opensearch2,opensearch3"
            - name: cluster.initial_master_nodes
              value: "opensearch1,opensearch2,opensearch3"
            # - name: discovery.type
            #   value: "single-node"
          ports:
            - name: publish
              containerPort: 9200
              protocol: TCP
            - name: node
              containerPort: 9300
              protocol: TCP
          volumeMounts:
            - name: opensearch2-data
              mountPath: /usr/share/opensearch/data
            - name: security-config
              subPath: config.yml
              mountPath: /usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml
            - name: opensearch-certs
              mountPath: "/certs"
              readOnly: true
          securityContext:
            privileged: true
            runAsUser: 1000
            runAsGroup: 0
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: opensearch2-data
          persistentVolumeClaim:
            claimName: opensearch2-data-pvc
        - name: security-config
          configMap: 
            name: opensearch-configmap
            items:
              - key: securityconfig.yml
                path: config.yml
              - key: generatecerts.sh
                path: generatecerts.sh
        - name: opensearch-certs
          secret:
            secretName: opensearch-certs
            items:
              - key: admin.pem
                path: certs/admin.pem
              - key: admin-key.pem
                path: certs/admin-key.pem
              - key: client.pem
                path: certs/client.pem
              - key: client-key.pem
                path: certs/client-key.pem
              - key: node1.pem
                path: certs/node1.pem
              - key: node1-key.pem
                path: certs/node1-key.pem
              - key: node2.pem
                path: certs/node2.pem
              - key: node2-key.pem
                path: certs/node2-key.pem
              - key: node3.pem
                path: certs/node3.pem
              - key: node3-key.pem
                path: certs/node3-key.pem
              - key: root-ca.pem
                path: certs/root-ca.pem
              - key: root-ca-key.pem
                path: certs/root-ca-key.pem
              - key: root-ca.srl
                path: certs/root-ca.srl
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: opensearch2
  name: opensearch2
  namespace: opensearch
spec:
  ports:
    - name: external
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: internal
      port: 9300
      protocol: TCP
      targetPort: 9300
  selector:
    run: opensearch2
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch2-data-pvc
  namespace: opensearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi