apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: zoo1
  name: zoo1
  namespace: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      run: zoo1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: zoo1
    spec:
      containers:
        - image: cithub/zookeeper
          imagePullPolicy: Always
          name: zoo1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: ZOO_MY_ID
              value: "1"
            - name: ZOO_SERVERS
              value: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
          ports:
            - name: server
              containerPort: 2888
              protocol: TCP
            - name: leader-election
              containerPort: 3888
              protocol: TCP
          # volumeMounts:
          #   - name: zoo1-volume
          #     mountPath: /datalog
          #   - name: zoo1-volume
          #     mountPath: /data
          #   - name: zoo1-volume
          #     mountPath: /logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      # volumes:
      #   - name: zoo1-volume
      #     persistentVolumeClaim:
      #       claimName: zoo1
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     run: zoo1
#   name: zoo1
#   namespace: zookeeper
# spec:
#   ports:
#     - name: client
#       port: 2181
#       protocol: TCP
#       targetPort: 2181
#     - name: server
#       port: 2888
#       protocol: TCP
#       targetPort: 2888
#     - name: leader-election
#       port: 3888
#       protocol: TCP
#       targetPort: 3888
#   selector:
#     run: zoo1
#   sessionAffinity: None
#   type: LoadBalancer
# status:
#   loadBalancer: {}
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: zoo1
#   labels:
#     run: zoo1
#   namespace: zookeeper
# spec:
#   storageClassName: hostpath
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/Users/hardikpatel/workbench/projects/cit/kube-deploys/zookeeper/data/zoo1"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: zoo1
#   namespace: zookeeper
# spec:
#   storageClassName: hostpath
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi