apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: zoo2
  name: zoo2
  namespace: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      run: zoo2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: zoo2
    spec:
      containers:
        - image: cithub/zookeeper
          imagePullPolicy: Always
          name: zoo2
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: ZOO_MY_ID
              value: "2"
            - name: ZOO_SERVERS
              value: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
          ports:
            - name: server
              containerPort: 2888
              protocol: TCP
            - name: leader-election
              containerPort: 3888
              protocol: TCP
          # volumeMounts:
          #   - name: zoo2-volume
          #     mountPath: /datalog
          #   - name: zoo2-volume
          #     mountPath: /data
          #   - name: zoo2-volume
          #     mountPath: /logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      # volumes:
      #   - name: zoo2-volume
      #     persistentVolumeClaim:
      #       claimName: zoo2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: zoo2
  name: zoo2
  namespace: zookeeper
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
      targetPort: 2181
    - name: server
      port: 2888
      protocol: TCP
      targetPort: 2888
    - name: leader-election
      port: 3888
      protocol: TCP
      targetPort: 3888
  selector:
    run: zoo2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: zoo2
#   labels:
#     run: zoo2
#   namespace: zookeeper
# spec:
#   storageClassName: hostpath
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/Users/hardikpatel/workbench/projects/cit/kube-deploys/zookeeper/data/zoo2"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: zoo2
#   namespace: zookeeper
# spec:
#   storageClassName: hostpath
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi