apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: druid-middlemanager
  name: druid-middlemanager
  namespace: druid
spec:
  replicas: 1
  selector:
    matchLabels:
      run: druid-middlemanager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: druid-middlemanager
      labels:
        run: druid-middlemanager
    spec:
      containers:
        - image: apache/druid:0.21.1
          imagePullPolicy: Always
          name: druid-middlemanager
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          args: ["middleManager"]
          env:
            - name: DRUID_SET_HOST
              value: "druid-middlemanager"
          envFrom:
            - configMapRef:
                name: druid-environment
          ports:
            - name: middlemanager
              containerPort: 8091
              protocol: TCP
          volumeMounts:
            - name: druid-common-runtime-properties
              mountPath: /opt/druid/conf/druid/cluster/_common/common.runtime.properties
              subPath: common.runtime.properties
            - name: middlemanager-runtime-properties
              mountPath: /opt/druid/conf/druid/cluster/data/middleManager/runtime.properties
              subPath: runtime.properties
            - name: druid-middlemanager-volume
              mountPath: /opt/druid/var
            - name: druid-shared-volume
              mountPath: /opt/shared
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: druid-common-runtime-properties
          configMap:
            name: druid-common-runtime-properties
        - name: middlemanager-runtime-properties
          configMap:
            name: middlemanager-runtime-properties
        - name: druid-middlemanager-volume
          persistentVolumeClaim:
            claimName: druid-middlemanager-volume
        - name: druid-shared-volume
          persistentVolumeClaim:
            claimName: druid-shared-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: druid-middlemanager
  name: druid-middlemanager
  namespace: druid
spec:
  ports:
    - name: inernal
      port: 8091
      protocol: TCP
      targetPort: 8091
  selector:
    run: druid-middlemanager
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: middlemanager-runtime-properties
  namespace: druid
data:
  runtime.properties: |
      druid.host=druid-middlemanager.druid
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: druid-middlemanager-volume
  labels:
    run: druid-middlemanager
  namespace: druid
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/hardikpatel/workbench/projects/kube-deploys/druid/data/middlemanager"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: druid-middlemanager-volume
  namespace: druid
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi