apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kafdrop
  name: kafdrop
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kafdrop
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kafdrop
    spec:
      containers:
        - image: obsidiandynamics/kafdrop:latest
          imagePullPolicy: Always
          name: kafdrop
          resources:
            requests:
              memory: "1024M"
              cpu: "800m"
            limits:
              memory: "1024M"
              cpu: "1000m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: KAFKA_BROKERCONNECT
              value: kafka1:9091,kafka2:9092,kafka3:9093
            - name: JVM_OPTS
              value: "-Xms1024M -Xmx1024M"
            - name: SERVER_SERVLET_CONTEXTPATH
              value: "/"
            - name: SCHEMAREGISTRY_CONNECT
              value: http://schema-registry:8081
          ports:
            - name: ui
              containerPort: 9000
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: kafdrop
  name: kafdrop
  namespace: kafka
spec:
  ports:
    - name: kafdrop
      port: 9001
      protocol: TCP
      targetPort: 9000
  selector:
    run: kafdrop
  sessionAffinity: None
  type: LoadBalancer
