apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kafka-ui
  name: kafka-ui
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kafka-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kafka-ui
    spec:
      containers:
        - image: ghcr.io/channelit/kafka-ui:latest
          imagePullPolicy: Always
          name: kafka-ui
          resources:
            requests:
              memory: "1024Mi"
              cpu: "400m"
            limits:
              memory: "1024Mi"
              cpu: "400m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          command: ["java", "-Dspring.config.additional-location=/config/config.yml", "-jar"]
          args: ["/opt/kafka-ui/kafka-ui.jar"]
          env:
            - name: CLUSTER_NAME
              value: cluster_1
          ports:
            - name: ui
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 9000
              scheme: "HTTP"
              path: "/actuator/health"
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 9000
              scheme: "HTTP"
              path: "/actuator/health"
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          volumeMounts:
              - name: kafka-ui-config-yml
                mountPath: /config
                readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: kafka-ui-config
          configMap:
            name: kafka-ui-config
        - name: kafka-ui-config-yml
          configMap:
            name: kafka-ui-config
            items:
                - key: "config.yml"
                  path: "config.yml"
                  mode: 0777
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: kafka-ui
  name: kafka-ui
  namespace: kafka
spec:
  ports:
    - name: kafka-ui
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    run: kafka-ui
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-config-env
  namespace: kafka
data:
  KAFKA_CLUSTER_0_NAME: ${CLUSTER_NAME}
  KAFKA_CLUSTER_0_BOOTSTRAPSERVERS: kafka1:9091,kafka2:9092,kafka3:9093
  KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
  KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
  KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";'
  SPRING_CONFIG_ADDITIONAL-LOCATION: /config/config.yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-config
  namespace: kafka
data:
  config.yml: |
    server:
      port: 9000
    # kafka:
      # clusters:
      #   - 
      #     name: ${CLUSTER_NAME}
      #     bootstrapServers: kafka1:9091,kafka2:9092,kafka3:9093
      #     schemaRegistry: http://schema-registry:8081
    # Create realm in keycloak to use this and set values accordingly
    # Comment/uncomment out following lines to disable/enable auth
    # auth:
    #   type: OAUTH2
    #   oauth2:
    #     client:
    #       keycloak:
    #         clientId: kafka-ui
    #         clientSecret: XfZKTgiZHaH4EEeAyVOzrtrye3OQ76rz
    #         scope: openid
    #         issuer-uri: http://keycloak.keycloak:8080/realms/kafka-ui
    #         user-name-attribute: preferred_username
    #         client-name: kafka-ui
    #         provider: keycloak
    #         custom-params:
    #           type: keycloak