##################################################################################################
# Keycloak
##################################################################################################
---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    name: keycloak
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      namespace: keycloak
      name: keycloak
      labels:
        app: keycloak
        name: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:17.0.1
        imagePullPolicy: Always
        env:
          - name: KEYCLOAK_ADMIN
            value: "admin"
          - name: KEYCLOAK_ADMIN_PASSWORD
            value: "admin"
          - name: KC_PROXY
            value: "edge"
        args: ["start-dev"]
        volumeMounts:
          - name: keycloak-realm
            mountPath: /keycloak/realm.json
            subPath: realm.json
        ports:
          - containerPort: 8080
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 2
      volumes:
        - name: keycloak-realm
          configMap:
            name: keycloak-realm
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    name: keycloak
spec:
  ports:
  - name: keycloak
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: keycloak
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  namespace: keycloak
data:
  realm.json: |
    {
      "realm": "envoy",
      "enabled": true,
      "users": [
        {
          "username": "user",
          "enabled": true,
          "credentials": [
            {
              "type": "password",
              "value": "user"
            }
          ],
          "realmRoles": [
            "user"
          ],
          "clientRoles": {
            "account": [
              "manage-account"
            ]
          }
        }
      ],
      "roles": {
        "realm": [
          {
            "name": "user",
            "description": "User privileges"
          },
          {
            "name": "admin",
            "description": "Administrator privileges"
          }
        ]
      },
      "defaultRoles": [
        "user"
      ],
      "clients": [
        {
          "clientId": "envoy",
          "enabled": true,
          "publicClient": true,
          "directAccessGrantsEnabled": true,
          "redirectUris": [
            "*"
          ],
          "webOrigins": [
            "*"
          ]
        }
      ]
    }