[zookeeper]
servers=[ "zoo1.zookeeper.svc.cluster.local:2181", "zoo2.zookeeper.svc.cluster.local:2181", "zoo3.zookeeper.svc.cluster.local:2181" ]
timeout=6
root-path="/burrow"

[cluster.local]
class-name="kafka"
servers=[ "kafka2.kafka.svc.cluster.local:29092" ]
topic-refresh=60
offset-refresh=30

[consumer.local]
class-name="kafka"
cluster="local"
servers=[ "kafka2.kafka.svc.cluster.local:29092" ]
group-denylist="^(console-consumer-|python-kafka-consumer-).*$"
group-allowlist=""

[consumer.local_zk]
class-name="kafka_zk"
cluster="local"
servers=[ "zoo1.zookeeper.svc.cluster.local:2181", "zoo2.zookeeper.svc.cluster.local:2181", "zoo3.zookeeper.svc.cluster.local:2181" ]
zookeeper-path="/kafka"
zookeeper-timeout=30
group-denylist="^(console-consumer-|python-kafka-consumer-).*$"
group-allowlist=""

[httpserver.default]
address=":8000"