[zookeeper]
servers=[ "zoo1.zookeeper.svc.cluster.local:2181", "zoo2.zookeeper.svc.cluster.local:2181", "zoo3.zookeeper.svc.cluster.local:2181" ]
timeout=6
root-path="/burrow"

[cluster.zoo]
class-name="kafka"
servers=[ "kafka2.kafka:29092" ]
topic-refresh=60
offset-refresh=30

[consumer.zoo]
class-name="kafka"
cluster="zoo"
servers=[ "kafka2.kafka:29092" ]
group-denylist="^(console-consumer-|python-kafka-consumer-).*$"
group-allowlist=""

[httpserver.default]
address=":8000"