apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: istio
  name: istio
  namespace: istio
spec:
  replicas: 1
  selector:
    matchLabels:
      run: istio
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: istio
    spec:
      containers:
        - image: cithub/kafka-streams
          imagePullPolicy: Always
          name: istio
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - name: ui
              containerPort: 8080
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: istio
  name: istio
  namespace: kafka
spec:
  ports:
    - name: istio
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: istio
  sessionAffinity: None
  type: LoadBalancer
