apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: solr3
  name: solr3
  namespace: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      run: solr3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: solr3
      labels:
        run: solr3
    spec:
      containers:
        - image: ghcr.io/channelit/solr:latest
          imagePullPolicy: Always
          name: solr3
          command: ["/bin/sh"]
          args: ["-c", "/var/solr/conf/solr-entrypoint.sh"]
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: ZK_HOST
              value: "zoo1.zookeeper:2181,zoo2.zookeeper:2181,zoo3.zookeeper:2181"
            - name: SOLR_HOST
              value: solr3.solr
            - name: SOLR_PORT
              value: "8983"
          ports:
            - name: server
              containerPort: 8983
          volumeMounts:
            - name: solr3-configmap
              mountPath: /var/solr/conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: solr3-configmap
          configMap:
            name: solr3-configmap
            items:
            - key: "solr-entrypoint.sh"
              path: "solr-entrypoint.sh"
              mode: 0777
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: solr3
  name: solr3
  namespace: solr
spec:
  ports:
    - name: external
      port: 8983
      protocol: TCP
      targetPort: 8983
  selector:
    run: solr3
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: solr3-configmap
  namespace: solr
data:
  solr-entrypoint.sh: |
      /opt/solr/bin/solr start -f -c -p 8983 -z $ZK_HOST/solr