apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: solr1
  name: solr1
  namespace: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      run: solr1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: solr1
      labels:
        run: solr1
    spec:
      containers:
        - image: ghcr.io/channelit/solr:latest
          imagePullPolicy: Always
          name: solr1
          command: ["/bin/sh"]
          args: ["-c", "/var/solr/conf/solr-entrypoint.sh"]
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: ZK_HOST
              value: "zoo1.zookeeper:2181,zoo2.zookeeper:2181,zoo3.zookeeper:2181"
            - name: SOLR_HOST
              value: solr1.solr
            - name: SOLR_PORT
              value: "8983"
            - name: SOLR_ADMIN_UI_DISABLED
              value: "false"
            - name: SOLR_JETTY_HOST
              value: "0.0.0.0"
          ports:
            - name: server
              containerPort: 8983
              protocol: TCP
          volumeMounts:
            - name: solr1-configmap
              mountPath: /var/solr/conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 8983
        runAsGroup: 8983
      terminationGracePeriodSeconds: 30
      volumes:
        - name: solr1-configmap
          configMap:
            name: solr1-configmap
            items:
            - key: "solr-entrypoint.sh"
              path: "solr-entrypoint.sh"
              mode: 0777
            - key: "solr.xml"
              path: "solr.xml"
            - key: "solrconfig.xml"
              path: "solrconfig.xml"
            - key: "solr-security.sh"
              path: "solr-security.sh"
            - key: "setup-certs.sh"
              path: "setup-certs.sh"
            - key: "setup-jks.sh"
              path: "setup-jks.sh"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: solr1
  name: solr1
  namespace: solr
spec:
  ports:
    - name: external
      port: 8983
      protocol: TCP
      targetPort: 8983
  selector:
    run: solr1
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: solr1-configmap
  namespace: solr
data:
  solr-entrypoint.sh: |
      ls /var/solr/conf
      /opt/solr/server/scripts/cloud-scripts/zkcli.sh -zkhost $ZK_HOST -cmd makepath /solr
      cp /var/solr/conf/solrconfig.xml /opt/solr/server/solr/configsets/_default/conf/.
      /opt/solr/bin/solr zk upconfig -n cit_ml -d /opt/solr/server/solr/configsets/_default -z $ZK_HOST/solr -r
      /opt/solr/bin/solr zk cp file:/var/solr/conf/solr.xml zk:/solr/solr.xml -z $ZK_HOST
      /opt/solr/bin/solr start -f -c -m 1g -z $ZK_HOST/solr
  solr.xml: |
      <?xml version="1.0" encoding="UTF-8" ?>
      <solr>
          <solrcloud>
              <str name="host">${host:}</str>
              <int name="hostPort">${jetty.port:8983}</int>
              <str name="hostContext">${hostContext:solr}</str>
              <bool name="genericCoreNodeNames">${genericCoreNodeNames:true}</bool>
              <int name="zkClientTimeout">${zkClientTimeout:30000}</int>
              <int name="distribUpdateSoTimeout">${distribUpdateSoTimeout:600000}</int>
              <int name="distribUpdateConnTimeout">${distribUpdateConnTimeout:60000}</int>
              <str name="zkCredentialsProvider">${zkCredentialsProvider:org.apache.solr.common.cloud.DefaultZkCredentialsProvider}</str>
              <str name="zkACLProvider">${zkACLProvider:org.apache.solr.common.cloud.DefaultZkACLProvider}</str>
          </solrcloud>
          <shardHandlerFactory name="shardHandlerFactory" class="HttpShardHandlerFactory">
              <int name="socketTimeout">${socketTimeout:600000}</int>
              <int name="connTimeout">${connTimeout:60000}</int>
          </shardHandlerFactory>
      </solr>
  solrconfig.xml: |
      <?xml version="1.0" encoding="UTF-8" ?>
      <config>
        <luceneMatchVersion>9.0</luceneMatchVersion>
        <lib dir="${solr.install.dir:../../../..}/modules/ltr/lib" regex=".*\.jar" />
        <dataDir>${solr.data.dir:}</dataDir>
        <directoryFactory name="DirectoryFactory"
                          class="${solr.directoryFactory:solr.NRTCachingDirectoryFactory}"/>
        <codecFactory class="solr.SchemaCodecFactory"/>
        <indexConfig>
          <lockType>${solr.lock.type:native}</lockType>
        </indexConfig>
        <updateHandler class="solr.DirectUpdateHandler2">
          <updateLog>
            <str name="dir">${solr.ulog.dir:}</str>
            <int name="numVersionBuckets">${solr.ulog.numVersionBuckets:65536}</int>
          </updateLog>
          <autoCommit>
            <maxTime>${solr.autoCommit.maxTime:15000}</maxTime>
            <openSearcher>false</openSearcher>
          </autoCommit>
          <autoSoftCommit>
            <maxTime>${solr.autoSoftCommit.maxTime:-1}</maxTime>
          </autoSoftCommit>
        </updateHandler>
        <query>
          <maxBooleanClauses>${solr.max.booleanClauses:1024}</maxBooleanClauses>
          <filterCache size="512"
                       initialSize="512"
                       autowarmCount="0"/>
          <queryResultCache size="512"
                            initialSize="512"
                            autowarmCount="0"/>
          <documentCache size="512"
                         initialSize="512"
                         autowarmCount="0"/>
          <cache name="perSegFilter"
                 class="solr.CaffeineCache"
                 size="10"
                 initialSize="0"
                 autowarmCount="10"
                 regenerator="solr.NoOpRegenerator" />
          <enableLazyFieldLoading>true</enableLazyFieldLoading>
          <queryResultWindowSize>20</queryResultWindowSize>
          <queryResultMaxDocsCached>200</queryResultMaxDocsCached>
          <listener event="newSearcher" class="solr.QuerySenderListener">
            <arr name="queries">
            </arr>
          </listener>
          <listener event="firstSearcher" class="solr.QuerySenderListener">
            <arr name="queries">
            </arr>
          </listener>
          <useColdSearcher>false</useColdSearcher>
        </query>
          <circuitBreakers enabled="true">
        </circuitBreakers>
        <requestDispatcher>
          <httpCaching never304="true" />
        </requestDispatcher>
        <requestHandler name="/select" class="solr.SearchHandler">
          <lst name="defaults">
            <str name="echoParams">explicit</str>
            <int name="rows">10</int>
          </lst>
        </requestHandler>
        <requestHandler name="/query" class="solr.SearchHandler">
          <lst name="defaults">
            <str name="echoParams">explicit</str>
            <str name="wt">json</str>
            <str name="indent">true</str>
          </lst>
        </requestHandler>
        <initParams path="/update/**,/query,/select,/spell">
          <lst name="defaults">
            <str name="df">_text_</str>
          </lst>
        </initParams>
        <searchComponent name="spellcheck" class="solr.SpellCheckComponent">
          <str name="queryAnalyzerFieldType">text_general</str>
          <lst name="spellchecker">
            <str name="name">default</str>
            <str name="field">_text_</str>
            <str name="classname">solr.DirectSolrSpellChecker</str>
            <str name="distanceMeasure">internal</str>
            <float name="accuracy">0.5</float>
            <int name="maxEdits">2</int>
            <int name="minPrefix">1</int>
            <int name="maxInspections">5</int>
            <int name="minQueryLength">4</int>
            <float name="maxQueryFrequency">0.01</float>
          </lst>
        </searchComponent>
        <requestHandler name="/spell" class="solr.SearchHandler" startup="lazy">
          <lst name="defaults">
            <str name="spellcheck.dictionary">default</str>
            <str name="spellcheck">on</str>
            <str name="spellcheck.extendedResults">true</str>
            <str name="spellcheck.count">10</str>
            <str name="spellcheck.alternativeTermCount">5</str>
            <str name="spellcheck.maxResultsForSuggest">5</str>
            <str name="spellcheck.collate">true</str>
            <str name="spellcheck.collateExtendedResults">true</str>
            <str name="spellcheck.maxCollationTries">10</str>
            <str name="spellcheck.maxCollations">5</str>
          </lst>
          <arr name="last-components">
            <str>spellcheck</str>
          </arr>
        </requestHandler>
        <searchComponent class="solr.HighlightComponent" name="highlight">
          <highlighting>
            <fragmenter name="gap"
                        default="true"
                        class="solr.highlight.GapFragmenter">
              <lst name="defaults">
                <int name="hl.fragsize">100</int>
              </lst>
            </fragmenter>
            <fragmenter name="regex"
                        class="solr.highlight.RegexFragmenter">
              <lst name="defaults">
                <int name="hl.fragsize">70</int>
                <float name="hl.regex.slop">0.5</float>
                <str name="hl.regex.pattern">[-\w ,/\n\&quot;&apos;]{20,200}</str>
              </lst>
            </fragmenter>
            <formatter name="html"
                       default="true"
                       class="solr.highlight.HtmlFormatter">
              <lst name="defaults">
                <str name="hl.simple.pre"><![CDATA[<em>]]></str>
                <str name="hl.simple.post"><![CDATA[</em>]]></str>
              </lst>
            </formatter>
            <encoder name="html"
                     class="solr.highlight.HtmlEncoder" />
            <fragListBuilder name="simple"
                             class="solr.highlight.SimpleFragListBuilder"/>
            <fragListBuilder name="single"
                             class="solr.highlight.SingleFragListBuilder"/>
            <fragListBuilder name="weighted"
                             default="true"
                             class="solr.highlight.WeightedFragListBuilder"/>
            <fragmentsBuilder name="default"
                              default="true"
                              class="solr.highlight.ScoreOrderFragmentsBuilder">
            </fragmentsBuilder>
            <fragmentsBuilder name="colored"
                              class="solr.highlight.ScoreOrderFragmentsBuilder">
              <lst name="defaults">
                <str name="hl.tag.pre"><![CDATA[
                     <b style="background:yellow">,<b style="background:lawgreen">,
                     <b style="background:aquamarine">,<b style="background:magenta">,
                     <b style="background:palegreen">,<b style="background:coral">,
                     <b style="background:wheat">,<b style="background:khaki">,
                     <b style="background:lime">,<b style="background:deepskyblue">]]></str>
                <str name="hl.tag.post"><![CDATA[</b>]]></str>
              </lst>
            </fragmentsBuilder>
            <boundaryScanner name="default"
                             default="true"
                             class="solr.highlight.SimpleBoundaryScanner">
              <lst name="defaults">
                <str name="hl.bs.maxScan">10</str>
                <str name="hl.bs.chars">.,!? &#9;&#10;&#13;</str>
              </lst>
            </boundaryScanner>
            <boundaryScanner name="breakIterator"
                             class="solr.highlight.BreakIteratorBoundaryScanner">
              <lst name="defaults">
                <str name="hl.bs.type">WORD</str>
                <str name="hl.bs.language">en</str>
                <str name="hl.bs.country">US</str>
              </lst>
            </boundaryScanner>
          </highlighting>
        </searchComponent>
        <updateProcessor class="solr.UUIDUpdateProcessorFactory" name="uuid"/>
        <updateProcessor class="solr.RemoveBlankFieldUpdateProcessorFactory" name="remove-blank"/>
        <updateProcessor class="solr.FieldNameMutatingUpdateProcessorFactory" name="field-name-mutating">
          <str name="pattern">[^\w-\.]</str>
          <str name="replacement">_</str>
        </updateProcessor>
        <updateProcessor class="solr.ParseBooleanFieldUpdateProcessorFactory" name="parse-boolean"/>
        <updateProcessor class="solr.ParseLongFieldUpdateProcessorFactory" name="parse-long"/>
        <updateProcessor class="solr.ParseDoubleFieldUpdateProcessorFactory" name="parse-double"/>
        <updateProcessor class="solr.ParseDateFieldUpdateProcessorFactory" name="parse-date">
          <arr name="format">
            <str>yyyy-MM-dd['T'[HH:mm[:ss[.SSS]][z</str>
            <str>yyyy-MM-dd['T'[HH:mm[:ss[,SSS]][z</str>
            <str>yyyy-MM-dd HH:mm[:ss[.SSS]][z</str>
            <str>yyyy-MM-dd HH:mm[:ss[,SSS]][z</str>
            <str>[EEE, ]dd MMM yyyy HH:mm[:ss] z</str>
            <str>EEEE, dd-MMM-yy HH:mm:ss z</str>
            <str>EEE MMM ppd HH:mm:ss [z ]yyyy</str>
          </arr>
        </updateProcessor>
        <updateProcessor class="solr.AddSchemaFieldsUpdateProcessorFactory" name="add-schema-fields">
          <lst name="typeMapping">
            <str name="valueClass">java.lang.String</str>
            <str name="fieldType">text_general</str>
            <lst name="copyField">
              <str name="dest">*_str</str>
              <int name="maxChars">256</int>
            </lst>
            <bool name="default">true</bool>
          </lst>
          <lst name="typeMapping">
            <str name="valueClass">java.lang.Boolean</str>
            <str name="fieldType">booleans</str>
          </lst>
          <lst name="typeMapping">
            <str name="valueClass">java.util.Date</str>
            <str name="fieldType">pdates</str>
          </lst>
          <lst name="typeMapping">
            <str name="valueClass">java.lang.Long</str>
            <str name="valueClass">java.lang.Integer</str>
            <str name="fieldType">plongs</str>
          </lst>
          <lst name="typeMapping">
            <str name="valueClass">java.lang.Number</str>
            <str name="fieldType">pdoubles</str>
          </lst>
        </updateProcessor>
        <updateRequestProcessorChain name="add-unknown-fields-to-the-schema" default="${update.autoCreateFields:true}"
                 processor="uuid,remove-blank,field-name-mutating,parse-boolean,parse-long,parse-double,parse-date,add-schema-fields">
          <processor class="solr.LogUpdateProcessorFactory"/>
          <processor class="solr.DistributedUpdateProcessorFactory"/>
          <processor class="solr.RunUpdateProcessorFactory"/>
        </updateRequestProcessorChain>
      </config>
  solr-security.sh: |
      #!/bin/bash
      if [[ ! -z "$SOLR_INIT" ]]; then
          echo "Setting up ZK"
          echo "ZK_HOST is " $ZK_HOST
          echo "SOLR_CONF is " $SOLR_CONF
          ./server/scripts/cloud-scripts/zkcli.sh -zkhost $ZK_HOST -cmd makepath /solr
          ./bin/solr zk upconfig -n cit_default -d "$SOLR_CONF"/_default -z "$ZK_HOST"/solr -r
          ./bin/solr zk cp file:"$SOLR_CONF"/solr.xml zk:/solr/solr.xml -z "$ZK_HOST"
      fi
      if [[ ! -z "$SOLR_SSL" ]]; then
        if [ ! -f /certs/solr-ssl.keystore.jks ]; then
          echo "Setting up SSL"
          ./server/scripts/cloud-scripts/zkcli.sh -zkhost "$ZK_HOST"/solr -cmd clusterprop -name urlScheme -val https
          ./setup-certs.sh
        fi
        echo "Setting Solr SSL Environment"
        export SOLR_SSL_KEY_STORE="/certs/solr-ssl.keystore.jks"
        export SOLR_SSL_KEY_STORE_PASSWORD="secret"
        export SOLR_SSL_TRUST_STORE="/certs/solr-ssl.keystore.jks"
        export SOLR_SSL_TRUST_STORE_PASSWORD="secret"
        export SOLR_SSL_NEED_CLIENT_AUTH="false"
        export SOLR_SSL_WANT_CLIENT_AUTH="false"
        export SOLR_SSL_CHECK_PEER_NAME="false"
        export SOLR_SSL_KEY_STORE_TYPE="JKS"
        export SOLR_SSL_TRUST_STORE_TYPE="JKS"
      fi
      exec "$@"
  setup-certs.sh: |
      #!/bin/sh
      keytool -genkeypair -alias solr-ssl -keyalg RSA -keysize 2048 -keypass secret -storepass secret -validity 9999 -keystore /certs/solr-ssl.keystore.jks -ext SAN=DNS:localhost,DNS:solr1,DNS:solr2,DNS:solr3,IP:192.168.1.3,IP:127.0.0.1 -dname "CN=$SOLR_HOST, OU=CITS, O=CITS, L=DC, ST=VA, C=USA"
      keytool -importkeystore -srckeystore /certs/solr-ssl.keystore.jks -srcstorepass secret -destkeystore /certs/solr-ssl.keystore.p12 -srcstoretype jks -deststoretype pkcs12 -deststorepass secret -noprompt
  setup-jks.sh: |
      #!/bin/bash
      #openssl rsa -in <(openssl s_client -connect solr1:443 -prexit 2>/dev/null) -out /certs/solr1.crt
      #openssl rsa -in <(openssl s_client -connect solr2:443 -prexit 2>/dev/null) -out /certs/solr2.crt
      #openssl rsa -in <(openssl s_client -connect solr3:443 -prexit 2>/dev/null) -out /certs/solr3.crt
      openssl s_client -connect solr1:8983 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /certs/solr1.crt
      openssl s_client -connect solr2:8983 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /certs/solr2.crt
      openssl s_client -connect solr3:8983 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /certs/solr3.crt
      keytool -import -alias solr1 -file /certs/solr1.crt -keystore /certs/solr-ssl.keystore.jks -storepass secret -noprompt
      keytool -import -alias solr2 -file /certs/solr2.crt -keystore /certs/solr-ssl.keystore.jks -storepass secret -noprompt
      keytool -import -alias solr3 -file /certs/solr3.crt -keystore /certs/solr-ssl.keystore.jks -storepass secret -noprompt

