apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kafka1
  name: kafka1
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kafka1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kafka1
    spec:
      containers:
        - image: cithub/kafka
          imagePullPolicy: Always
          name: kafka1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - name: server
              containerPort: 9092
              protocol: TCP
            - name: leader-election
              containerPort: 9092
              protocol: TCP
          volumeMounts:
            - name: kafka1-volume
              mountPath: /conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: kafka1-volume
          persistentVolumeClaim:
            claimName: kafka1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: kafka1
  name: kafka1
  namespace: kafka
spec:
  ports:
    - name: client
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    run: kafka1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka1
  labels:
    run: kafka1
  namespace: kafka
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/hardikpatel/workbench/projects/cit/kube-deploys/kafka/config/kafka1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka1
  namespace: kafka
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi