apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cmak
  name: cmak
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cmak
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: cmak
    spec:
      containers:
        - image: cithub/kafka-cmak
          imagePullPolicy: Always
          name: cmak
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: ZK_HOSTS
              value: zoo1.zookeeper.svc.cluster.local:2181,zoo2.zookeeper.svc.cluster.local:2181,zoo3.zookeeper.svc.cluster.local:2181/kafka
          ports:
            - name: ui
              containerPort: 9000
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: cmak
  name: cmak
  namespace: kafka
spec:
  ports:
    - name: ui
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    run: cmak
  sessionAffinity: None
  type: LoadBalancer