apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: postgres
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      run: postgres
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: postgres
      labels:
        run: postgres
    spec:
      containers:
        - image: postgres:12
          imagePullPolicy: Always
          name: postgres
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          args: ["-c", "config_file=/data/postgresql.conf"]
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: cits
            - name: POSTGRES_PASSWORD
              value: admin
          ports:
            - name: db
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: postgres-volume
              mountPath: /data/postgresql.conf
              subPath: postgresql.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: postgres-volume
          configMap:
            name: postgres-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: postgres
  name: postgres
  namespace: postgres
spec:
  ports:
    - name: db
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    run: postgres
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres
data:
  postgresql.conf: |
      listen_addresses = '*'
      max_connections = 100
      shared_buffers = 128MB
      datestyle = 'iso, mdy'
      timezone = 'Etc/UTC'
      lc_monetary = 'en_US.utf8'
      lc_numeric = 'en_US.utf8'
      lc_time = 'en_US.utf8'
      wal_level = logical
      max_wal_senders = 4
      max_replication_slots = 4