apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
    - name: "mongo"
      port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: mongo
spec:
  serviceName: "mongo" 
  replicas: 2
  selector: 
    matchLabels: 
      app: "mongo"
  template: 
    metadata: 
      labels: 
        app: "mongo"
    spec: 
      containers: 
        - name: "mongo"
          image: "mongo"
          imagePullPolicy: "Always"
          env: 
            - name: "MONGO_INITDB_ROOT_USERNAME"
              value: "admin"
              
            - name: "MONGO_INITDB_ROOT_PASSWORD"
              value: "admin"
              
          ports: 
            - containerPort: 27017
              name: "mongo"
              
          volumeMounts: 
            - name: "mongo-persistent-storage"
              mountPath: "/data/db"
              
      volumes: 
        - name: "mongo-persistent-storage"
          persistentVolumeClaim: 
            claimName: "mongodb-pvc"