apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mongo-pvc
  namespace: mongo
  labels: 
    app: mongo
spec: 
  accessModes:
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 2Gi